### ISSUE TITLE
Documentation / user guide

### ISSUE THREAD

**Issue by websciencetrust** [webobservatory/webobservatory#1]
Do we have a document describing usage guidelines?

**Comment by xgfd** [comment]
We have a [brief tutorial](http://webobservatory.soton.ac.uk/howto) on using the WO and its API. Also there's [an example](http://webobservatory.soton.ac.uk/wo/visualisation#5489d93e5d38cda3271d843d) about how to consume static datasets and live-streams via the WO API. A Github link of the example is provided.
