### ISSUE TITLE
Authentication problems from R programming language using cURL

### ISSUE THREAD

**Issue by m-l-r** [webobservatory/webobservatory#5]
response is just "Unauthorised" even though credentials are ok.

**Comment by xgfd** [comment]
solved.

**Comment by m-l-r** [comment]
this is still an issue. the problem is that while the postForm call works fine and an access token is responded, the subsequent get requests leads to a unauthorised error.

code example:

library(RCurl)
library(RJSONIO)

curl = getCurlHandle()

resp <- postForm("https://webobservatory.soton.ac.uk/oauth/token",
         "grant_type" = "password",
         "client_id" = "54fed4c0baf7899b679d59d0",
         "client_secret" = "de780a79c3986c6f",
         "username" = "USERNAME",
         "password" = "PASSWORD",
         style = "POST", .opts = list(ssl.verifypeer = FALSE), curl=curl)

tokenObj <- fromJSON(resp)

getURL("https://webobservatory.soton.ac.uk/api/wo/548047c832582f2c45520ce7/endpoint?query={}", curl=curl, httpheader = c(Authorisation=paste(tokenObj$token_type, " ",tokenObj$access_token,sep='')), .opts = list(ssl.verifypeer = FALSE),verbose=TRUE)

**Comment by xgfd** [comment]
I know nothing about R I'm afraid. Could you track what have been sent to the server? The API is working fine so I closed the issue.
